version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    build: .
    ports:
      - "8081:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://backend_user:backend_password@postgres:5432/backend_db
      REDIS_URL: redis://redis:6379
      PORT: 3000
      JWT_ACCESS_SECRET: your_access_secret
      JWT_REFRESH_SECRET: your_refresh_secret
      ACCESS_TOKEN_TTL: 900
      REFRESH_TOKEN_TTL: 1209600
      S3_ACCESS_KEY: your_s3_access_key
      S3_SECRET_KEY: your_s3_secret_key
      S3_REGION: us-east-1
      S3_BUCKET: your_bucket
volumes:
  postgres_data:
  redis_data: