name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: db
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db
        run: npx prisma generate
      - name: Run tests
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db
        run: npm test --silent